### ISSUE TITLE
Lift & Shift migration pattern is not clear in terms of how to export historical, soft-deleted versions from API for FHIR

### ISSUE THREAD

**Issue by UmarMohamedUsman** [Azure/apiforfhir-migration-tool#43]
**Describe the Issue **

The following [Lift & Shift migration pattern ](https://github.com/Azure/apiforfhir-migration-tool/blob/main/lift-and-shift-resources/Liftandshiftresources_README.md) guidance is not very clear or it doesn't explicitly state in terms of how to export historical, soft-deleted versions from API for FHIR. 

On the step 1.1, it does refer to [query parameters](https://learn.microsoft.com/en-us/azure/healthcare-apis/azure-api-for-fhir/export-data#query-parameters) where we've includeAssociatedData parameter which can be used to export historical, soft-deleted versions. But this can be easily missed. Since many customers do use historical, soft-deleted versions, it would be good to call this out explicitly in the export and import section.

**Comment by evachen96** [comment]
Thanks Umar! We will be updating the documentation.

**Comment by evachen96** [comment]
Documentation has been updated, thanks!
